/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Dialogc */

#ifndef _Included_Dialogc
#define _Included_Dialogc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Dialogc
 * Method:    parseConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Dialogc_parseConfig
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
